
version: "3"
services:
  flowbuilder-fe:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: sh -c "npm run start"
    volumes:
      - ./client:/home/app/client
      - /home/app/client/node_modules
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.mi.tmy.io/v1
      NEXT_PUBLIC_NETWORK_API_URL: http://flowbuilder-be:3001/v1
  flowbuilder-be:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: sh -c "npm run db-migrate && npm run run-prod"
    volumes:
      - ./api:/home/app/api
      - /home/app/api/node_modules
