version: "3"
services:
  flowbuilder-fe:
    container_name: flowbuilder-fe
    build: ./client
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/app/client
      - /home/app/client/node_modules
    working_dir: /home/app/client
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/v1
      NEXT_PUBLIC_NETWORK_API_URL: http://flowbuilder-be:3001/v1
  flowbuilder-be:
    container_name: flowbuilder-be
    build: ./api
    command: sh -c "npm run db-migrate && npm run run-dev"
    restart: always
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: flowbuilder
      DB_HOST: flowbuilder-db
      DB_PORT: 5432
      DB_TEST_HOST: flowbuilder-db-test
    ports:
      - 3001:3001
    volumes:
      - ./api:/home/app/api
      - /home/app/api/node_modules
    working_dir: /home/app/api
    restart: on-failure
    depends_on:
      - flowbuilder-db
      - flowbuilder-db-test
  flowbuilder-db:
    container_name: flowbuilder-db
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=flowbuilder
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  flowbuilder-db-test:
    container_name: flowbuilder-db-test
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=flowbuilder
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/data-test/postgres:/var/lib/postgresql/data
    ports:
      - 5430:5432
