apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "micompass-ui.fullname" . }}
  labels:
    {{- include "micompass-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "micompass-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "micompass-ui.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "micompass-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $k, $v := $.Values.env }}
            - name: {{ quote $k }}
              value: {{ quote $v }}
            {{- end }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databaseExistingSecret }}
                  key: db-connection-string
          volumeMounts:
          - mountPath: /var/lib/rancher
            name: rancher-dir
          - mountPath: /etc/rancher/k3s
            name: k3s-dir
          - mountPath: /usr/local/bin/k3s
            name: k3s-binary
      volumes:
      - name: rancher-dir
        hostPath:
          path: /var/lib/rancher
      - name: k3s-dir
        hostPath:
          path: /etc/rancher/k3s
      - name: k3s-binary
        hostPath:
          path: /usr/local/bin/k3s
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
