apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "micompass-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}}
  labels:
    {{- include "micompass-ui.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/exec
      - pods/portforward
      - pods/proxy
      - services
      - endpoints
      - configmaps
      - secrets
      - persistentvolumeclaims
      - namespaces
      - nodes
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "create"
