{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "micompass-ui.serviceAccountName" . }}
  labels:
{{ include "micompass-ui.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "micompass-ui.serviceAccountName" . }}-token
  annotations:
    kubernetes.io/service-account.name: {{ include "micompass-ui.serviceAccountName" . }}
  labels:
{{ include "micompass-ui.labels" . | nindent 4 }}
{{- end -}}
